# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now=True, verbose_name='检查日期')),
                ('process_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('zb_file', models.FileField(upload_to='uploads', verbose_name='招标文件')),
                ('tb_file_in', models.FileField(upload_to='uploads', verbose_name='投标文件')),
                ('lowmistake_check', models.BooleanField(default=True, verbose_name='低级错误检查')),
                ('filestyle_check', models.BooleanField(default=True, verbose_name='文件格式检查')),
                ('wrongword_check', models.BooleanField(default=True, verbose_name='错别字检查')),
                ('tbprice_check', models.BooleanField(default=True, verbose_name='投标价格检查')),
                ('tb_file_out', models.FilePathField(blank=True, null=True, verbose_name='投标文件下载')),
                ('check_result', models.TextField(blank=True, null=True, verbose_name='检查结果')),
            ],
        ),
    ]
