# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='模版名称')),
                ('tempfile', models.FileField(upload_to='uploads/temp', verbose_name='模版文件')),
                ('memo', models.TextField(verbose_name='备注')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='模版修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('profile', models.FileField(upload_to='uploads/profile', verbose_name='配置文件')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('download_file', models.FilePathField(verbose_name='文件下载')),
            ],
        ),
        migrations.CreateModel(
            name='TechContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='标题名')),
                ('level', models.IntegerField(verbose_name='标题级别')),
                ('memo', models.TextField(verbose_name='备注')),
                ('uptitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TechContent', verbose_name='上级标题')),
            ],
        ),
        migrations.CreateModel(
            name='TechTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='模版名称')),
                ('memo', models.TextField(verbose_name='备注')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='模版修改时间')),
                ('tech_content', models.ManyToManyField(to='app01.TechContent', verbose_name='目录')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('role', models.CharField(blank=True, max_length=16, null=True, verbose_name='角色')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='techtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='属主'),
        ),
        migrations.AddField(
            model_name='techcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='属主'),
        ),
        migrations.AddField(
            model_name='submitfile',
            name='tech_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TechTemplate', verbose_name='技术方案模版'),
        ),
        migrations.AddField(
            model_name='submitfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='属主'),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.TechContent', verbose_name='对应目录'),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserProfile', verbose_name='属主'),
        ),
    ]
